version: '3.8'

services:
  shopping-list:
    build: .
    container_name: shopping-list-app
    ports:
      - "3000:80"
    restart: unless-stopped
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    volumes:
      # Optional: Mount for development (uncomment to enable live reload)
      # - ./shopping-list.html:/usr/share/nginx/html/index.html:ro
      - nginx-logs:/var/log/nginx
    networks:
      - shopping-list-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  nginx-logs:
    driver: local

networks:
  shopping-list-network:
    driver: bridge