version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: shopping-list-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: shopping_list
      POSTGRES_USER: shopping_user
      POSTGRES_PASSWORD: shopping_password
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - shopping-list-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U shopping_user -d shopping_list"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Go Backend API
  backend:
    build: 
      context: ./backend-go
      dockerfile: Dockerfile
    container_name: shopping-list-backend-go
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=shopping_list
      - DB_USER=shopping_user
      - DB_PASSWORD=shopping_password
      - JWT_SECRET=your-super-secret-jwt-key-change-this-in-production-please
      - JWT_EXPIRES_IN=7d
      - PORT=3001
      - CORS_ALLOWED_ORIGINS=http://localhost:3000
      # OIDC Configuration
      - OIDC_CLIENT_ID=${OIDC_CLIENT_ID:-}
      - OIDC_CLIENT_SECRET=${OIDC_CLIENT_SECRET:-}
      - OIDC_DISCOVERY_URL=${OIDC_DISCOVERY_URL:-https://auth.mkomanek.eu/application/o/shopping-list/.well-known/openid_configuration}
      - OIDC_REDIRECT_URI=${OIDC_REDIRECT_URI:-http://localhost:3000/auth/oidc/callback}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - shopping-list-network

  # SvelteKit Frontend
  frontend:
    build: 
      context: ./frontend-svelte
      dockerfile: Dockerfile
    container_name: shopping-list-frontend-svelte
    ports:
      - "3000:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - API_URL=http://backend:3001
      - PUBLIC_API_URL=http://localhost:3001
    depends_on:
      - backend
    networks:
      - shopping-list-network

volumes:
  postgres-data:
    driver: local

networks:
  shopping-list-network:
    driver: bridge